"""A curated reference list of common grocery items, used by the recipe
importer to suggest a product name + a sensible purchase/stock unit pair
for an ingredient that doesn't already match anything in a household's own
Grocy instance (see _match_grocery_reference and its use in
_ws_match_recipe_ingredients, in __init__.py).

This is a STARTING POINT, not an authority - matches are always shown to
the person for review (they land in the existing "+ Add new product to
Grocy" mini-form, editable before anything is actually created), never
created in Grocy automatically. Extending this list over time is
encouraged and low-risk: it's plain data, no other code needs to change to
add, remove, or tweak an entry.

Two unit fields per item:
  - purchase_unit: what it's typically SOLD in (e.g. milk by the gallon,
    flour by the pound, eggs by the dozen) - this becomes the suggested
    product's qu_id_purchase.
  - stock_unit: what it's typically USED/tracked in, which for a lot of
    ingredients is the same as how it's bought (a can of beans is a can
    either way), but for some kitchen staples is a smaller cooking
    measurement recipes actually call for (milk by the cup, flour by the
    cup, butter by the tablespoon) - this becomes qu_id_stock.

`factor` (stock units per one purchase unit, matching Grocy's own
"quantity per container" concept - see _ws_create_grocy_product) is only
set for a small, deliberately conservative set of items where the
conversion is either an exact unit-of-measure fact (16 cups to a gallon, 4
cups to a quart, 12 eggs to a dozen, 32 tablespoons to a pound of butter)
or a widely-cited baking reference figure (King Arthur Baking's flour/
sugar/rice/oat weights-per-cup). Every other item deliberately leaves
purchase_unit == stock_unit rather than inventing an ingredient-density
number that hasn't actually been checked - a correct name and a real
default unit is still useful on its own, and nothing stops someone from
setting their own conversion afterward (or using the "+ Add new unit…"
option) if they want the split.
"""
from __future__ import annotations

# (name, aliases, category, purchase_unit, stock_unit, factor)
_RAW_REFERENCE_ROWS: list[tuple[str, tuple[str, ...], str, str, str, float | None]] = [
    # ------------------------------------------------------------------
    # Produce - vegetables
    # ------------------------------------------------------------------
    ("Yellow Onion", ("onion", "onions", "yellow onions"), "Produce", "each", "each", None),
    ("Red Onion", ("red onions",), "Produce", "each", "each", None),
    ("Garlic", ("garlic", "garlic clove", "cloves garlic", "clove of garlic"), "Produce", "head", "clove", 10),
    ("Russet Potato", ("potato", "potatoes", "russet potatoes"), "Produce", "pound", "pound", None),
    ("Sweet Potato", ("sweet potatoes", "yams"), "Produce", "pound", "pound", None),
    ("Carrot", ("carrots",), "Produce", "pound", "pound", None),
    ("Celery", ("celery stalk", "celery stalks"), "Produce", "bunch", "stalk", 8),
    ("Bell Pepper", ("bell peppers", "green pepper", "red pepper", "peppers"), "Produce", "each", "each", None),
    ("Jalapeño Pepper", ("jalapeno", "jalapenos", "jalapeño"), "Produce", "each", "each", None),
    ("Tomato", ("tomatoes", "roma tomato", "roma tomatoes"), "Produce", "pound", "each", None),
    ("Cherry Tomatoes", ("grape tomatoes",), "Produce", "pint", "pint", None),
    ("Cucumber", ("cucumbers",), "Produce", "each", "each", None),
    ("Zucchini", ("zucchinis",), "Produce", "each", "each", None),
    ("Yellow Squash", ("summer squash",), "Produce", "each", "each", None),
    ("Broccoli", ("broccoli florets", "broccoli crown"), "Produce", "pound", "pound", None),
    ("Cauliflower", ("cauliflower head",), "Produce", "each", "each", None),
    ("Spinach", ("baby spinach", "spinach leaves"), "Produce", "bag", "cup", None),
    ("Kale", ("kale leaves",), "Produce", "bunch", "cup", None),
    ("Romaine Lettuce", ("romaine", "romaine heart", "romaine hearts"), "Produce", "each", "each", None),
    ("Iceberg Lettuce", ("lettuce", "iceberg"), "Produce", "each", "each", None),
    ("Green Cabbage", ("cabbage", "cabbages"), "Produce", "each", "each", None),
    ("Mushroom", ("mushrooms", "button mushrooms", "cremini mushrooms", "white mushrooms"), "Produce", "pound", "pound", None),
    ("Corn on the Cob", ("corn", "ears of corn", "sweet corn"), "Produce", "each", "each", None),
    ("Green Beans", ("string beans",), "Produce", "pound", "pound", None),
    ("Peas", ("green peas", "english peas"), "Produce", "pound", "pound", None),
    ("Asparagus", ("asparagus spears",), "Produce", "pound", "pound", None),
    ("Brussels Sprouts", ("brussel sprouts",), "Produce", "pound", "pound", None),
    ("Eggplant", ("eggplants", "aubergine"), "Produce", "each", "each", None),
    ("Radish", ("radishes",), "Produce", "bunch", "bunch", None),
    ("Beet", ("beets", "beetroot"), "Produce", "bunch", "bunch", None),
    ("Turnip", ("turnips",), "Produce", "each", "each", None),
    ("Green Onion", ("scallion", "scallions", "green onions", "spring onion"), "Produce", "bunch", "bunch", None),
    ("Leek", ("leeks",), "Produce", "each", "each", None),
    ("Fresh Ginger", ("ginger root", "ginger"), "Produce", "each", "tablespoon", None),
    ("Avocado", ("avocados",), "Produce", "each", "each", None),
    ("Pumpkin", ("pie pumpkin", "sugar pumpkin"), "Produce", "each", "each", None),
    ("Butternut Squash", ("butternut squash",), "Produce", "each", "each", None),
    ("Artichoke", ("artichokes",), "Produce", "each", "each", None),
    ("Corn Tortillas", (), "Bakery", "package", "each", None),
    ("Shallot", ("shallots",), "Produce", "each", "each", None),
    ("Snow Peas", ("snap peas", "sugar snap peas"), "Produce", "pound", "pound", None),
    ("Okra", (), "Produce", "pound", "pound", None),
    ("Fennel Bulb", ("fennel",), "Produce", "each", "each", None),
    ("Parsnip", ("parsnips",), "Produce", "pound", "pound", None),
    ("Rutabaga", (), "Produce", "each", "each", None),
    ("Bok Choy", (), "Produce", "each", "each", None),
    ("Napa Cabbage", (), "Produce", "each", "each", None),
    ("Red Cabbage", (), "Produce", "each", "each", None),
    ("Watercress", (), "Produce", "bunch", "cup", None),
    ("Arugula", ("rocket",), "Produce", "bag", "cup", None),
    ("Swiss Chard", ("chard",), "Produce", "bunch", "cup", None),
    ("Collard Greens", (), "Produce", "bunch", "cup", None),
    ("Mustard Greens", (), "Produce", "bunch", "cup", None),
    ("Endive", (), "Produce", "each", "each", None),
    ("Radicchio", (), "Produce", "each", "each", None),
    ("Bean Sprouts", (), "Produce", "pound", "cup", None),
    ("Acorn Squash", (), "Produce", "each", "each", None),
    ("Spaghetti Squash", (), "Produce", "each", "each", None),
    ("Delicata Squash", (), "Produce", "each", "each", None),
    ("Poblano Pepper", ("poblano peppers", "poblanos"), "Produce", "each", "each", None),
    ("Serrano Pepper", ("serrano peppers",), "Produce", "each", "each", None),
    ("Habanero Pepper", ("habanero peppers",), "Produce", "each", "each", None),
    ("Anaheim Pepper", (), "Produce", "each", "each", None),
    ("Sweet Onion", ("vidalia onion",), "Produce", "each", "each", None),
    ("Horseradish Root", (), "Produce", "each", "tablespoon", None),
    ("Jicama", (), "Produce", "each", "cup", None),
    ("Daikon Radish", (), "Produce", "each", "cup", None),
    # ------------------------------------------------------------------
    # Produce - fruits
    # ------------------------------------------------------------------
    ("Banana", ("bananas",), "Produce", "each", "each", None),
    ("Apple", ("apples",), "Produce", "each", "each", None),
    ("Orange", ("oranges",), "Produce", "each", "each", None),
    ("Lemon", ("lemons",), "Produce", "each", "each", None),
    ("Lime", ("limes",), "Produce", "each", "each", None),
    ("Grapes", ("grape",), "Produce", "pound", "pound", None),
    ("Strawberry", ("strawberries",), "Produce", "pound", "cup", None),
    ("Blueberry", ("blueberries",), "Produce", "pint", "cup", None),
    ("Raspberry", ("raspberries",), "Produce", "pint", "cup", None),
    ("Blackberry", ("blackberries",), "Produce", "pint", "cup", None),
    ("Watermelon", (), "Produce", "each", "cup", None),
    ("Cantaloupe", (), "Produce", "each", "cup", None),
    ("Honeydew Melon", ("honeydew",), "Produce", "each", "cup", None),
    ("Pineapple", ("pineapples",), "Produce", "each", "cup", None),
    ("Mango", ("mangoes", "mangos"), "Produce", "each", "each", None),
    ("Peach", ("peaches",), "Produce", "each", "each", None),
    ("Pear", ("pears",), "Produce", "each", "each", None),
    ("Plum", ("plums",), "Produce", "each", "each", None),
    ("Cherry", ("cherries",), "Produce", "pound", "cup", None),
    ("Kiwi", ("kiwis", "kiwifruit"), "Produce", "each", "each", None),
    ("Pomegranate", ("pomegranates",), "Produce", "each", "each", None),
    ("Grapefruit", ("grapefruits",), "Produce", "each", "each", None),
    ("Coconut", ("coconuts", "fresh coconut"), "Produce", "each", "cup", None),
    ("Fig", ("figs",), "Produce", "each", "each", None),
    ("Dates", ("date", "medjool dates"), "Produce", "pound", "each", None),
    ("Apricot", ("apricots",), "Produce", "each", "each", None),
    ("Nectarine", ("nectarines",), "Produce", "each", "each", None),
    ("Cranberries", ("cranberry", "fresh cranberries"), "Produce", "bag", "cup", None),
    ("Papaya", ("papayas",), "Produce", "each", "each", None),
    ("Tangerine", ("tangerines", "clementine", "clementines"), "Produce", "each", "each", None),
    ("Star Fruit", ("carambola",), "Produce", "each", "each", None),
    ("Passion Fruit", (), "Produce", "each", "each", None),
    ("Guava", ("guavas",), "Produce", "each", "each", None),
    ("Persimmon", ("persimmons",), "Produce", "each", "each", None),
    ("Dragon Fruit", (), "Produce", "each", "each", None),
    ("Lychee", ("lychees",), "Produce", "pound", "each", None),
    ("Rhubarb", (), "Produce", "pound", "cup", None),
    ("Plantain", ("plantains",), "Produce", "each", "each", None),
    ("Currants", ("dried currants",), "Produce", "bag", "cup", None),
    ("Gooseberries", (), "Produce", "pint", "cup", None),
    ("Kumquat", ("kumquats",), "Produce", "each", "each", None),
    ("Blood Orange", ("blood oranges",), "Produce", "each", "each", None),
    ("Meyer Lemon", ("meyer lemons",), "Produce", "each", "each", None),
    # ------------------------------------------------------------------
    # Fresh herbs
    # ------------------------------------------------------------------
    ("Fresh Basil", ("basil", "basil leaves"), "Produce", "bunch", "tablespoon", None),
    ("Fresh Cilantro", ("cilantro", "coriander leaves"), "Produce", "bunch", "tablespoon", None),
    ("Fresh Parsley", ("parsley",), "Produce", "bunch", "tablespoon", None),
    ("Fresh Mint", ("mint", "mint leaves"), "Produce", "bunch", "tablespoon", None),
    ("Fresh Rosemary", ("rosemary",), "Produce", "package", "tablespoon", None),
    ("Fresh Thyme", ("thyme sprigs",), "Produce", "package", "tablespoon", None),
    ("Fresh Dill", ("dill",), "Produce", "bunch", "tablespoon", None),
    ("Fresh Oregano", (), "Produce", "package", "tablespoon", None),
    ("Fresh Sage", ("sage leaves",), "Produce", "package", "tablespoon", None),
    ("Fresh Chives", (), "Produce", "package", "tablespoon", None),
    ("Fresh Tarragon", (), "Produce", "package", "tablespoon", None),
    ("Fresh Marjoram", (), "Produce", "package", "tablespoon", None),
    ("Lemongrass", (), "Produce", "each", "tablespoon", None),
    ("Curry Leaves", (), "Produce", "package", "each", None),
    ("Fresh Bay Leaves", (), "Produce", "package", "each", None),
    # ------------------------------------------------------------------
    # Dairy & eggs
    # ------------------------------------------------------------------
    ("Whole Milk", ("milk", "2% milk", "skim milk", "reduced fat milk"), "Dairy", "gallon", "cup", 16),
    ("Heavy Cream", ("heavy whipping cream", "whipping cream"), "Dairy", "pint", "cup", 2),
    ("Half and Half", (), "Dairy", "pint", "cup", 2),
    ("Buttermilk", (), "Dairy", "quart", "cup", 4),
    ("Sour Cream", (), "Dairy", "each", "cup", None),
    ("Plain Yogurt", ("yogurt",), "Dairy", "each", "cup", None),
    ("Greek Yogurt", (), "Dairy", "each", "cup", None),
    ("Unsalted Butter", ("butter", "salted butter"), "Dairy", "pound", "tablespoon", 32),
    ("Margarine", (), "Dairy", "pound", "tablespoon", 32),
    ("Cream Cheese", (), "Dairy", "each", "ounce", None),
    ("Cheddar Cheese", ("shredded cheddar",), "Dairy", "pound", "cup", None),
    ("Mozzarella Cheese", ("shredded mozzarella",), "Dairy", "pound", "cup", None),
    ("Parmesan Cheese", ("grated parmesan", "parmesan"), "Dairy", "each", "cup", None),
    ("Feta Cheese", (), "Dairy", "each", "cup", None),
    ("Cottage Cheese", (), "Dairy", "each", "cup", None),
    ("Ricotta Cheese", (), "Dairy", "each", "cup", None),
    ("Eggs", ("egg", "large eggs"), "Dairy", "dozen", "each", 12),
    ("Whipped Cream", ("cool whip",), "Dairy", "each", "cup", None),
    ("String Cheese", (), "Dairy", "package", "each", None),
    ("Swiss Cheese", (), "Dairy", "pound", "slice", None),
    ("Provolone Cheese", ("provolone",), "Dairy", "pound", "slice", None),
    ("American Cheese", ("american cheese slices",), "Dairy", "pound", "slice", None),
    ("Gouda Cheese", ("gouda",), "Dairy", "each", "ounce", None),
    ("Brie Cheese", ("brie",), "Dairy", "each", "ounce", None),
    ("Blue Cheese", ("blue cheese crumbles",), "Dairy", "each", "cup", None),
    ("Monterey Jack Cheese", ("monterey jack",), "Dairy", "pound", "cup", None),
    ("Pepper Jack Cheese", ("pepper jack",), "Dairy", "pound", "cup", None),
    ("Goat Cheese", (), "Dairy", "each", "ounce", None),
    ("Kefir", (), "Dairy", "each", "cup", None),
    ("Chocolate Milk", (), "Dairy", "gallon", "cup", 16),
    ("Ghee", ("clarified butter",), "Dairy", "each", "tablespoon", None),
    ("Egg Whites", (), "Dairy", "each", "each", None),
    ("Egg Substitute", (), "Dairy", "each", "cup", None),
    # ------------------------------------------------------------------
    # Meat & poultry
    # ------------------------------------------------------------------
    ("Chicken Breast", ("chicken breasts", "boneless skinless chicken breast", "boneless chicken breast"), "Meat", "pound", "pound", None),
    ("Chicken Thighs", ("chicken thigh",), "Meat", "pound", "pound", None),
    ("Whole Chicken", (), "Meat", "each", "each", None),
    ("Ground Chicken", (), "Meat", "pound", "pound", None),
    ("Ground Beef", ("hamburger meat",), "Meat", "pound", "pound", None),
    ("Ground Turkey", (), "Meat", "pound", "pound", None),
    ("Ground Pork", (), "Meat", "pound", "pound", None),
    ("Beef Steak", ("steak", "ribeye", "sirloin steak", "strip steak"), "Meat", "pound", "pound", None),
    ("Beef Roast", ("chuck roast", "pot roast"), "Meat", "pound", "pound", None),
    ("Beef Stew Meat", ("stew meat",), "Meat", "pound", "pound", None),
    ("Pork Chops", ("pork chop",), "Meat", "pound", "pound", None),
    ("Pork Tenderloin", (), "Meat", "pound", "pound", None),
    ("Bacon", (), "Meat", "pound", "slice", 16),
    ("Sausage", ("italian sausage", "breakfast sausage"), "Meat", "pound", "each", None),
    ("Ham", ("ham steak",), "Meat", "pound", "pound", None),
    ("Turkey Breast", (), "Meat", "pound", "pound", None),
    ("Lamb", ("lamb chops", "leg of lamb"), "Meat", "pound", "pound", None),
    ("Veal", (), "Meat", "pound", "pound", None),
    ("Hot Dogs", ("hot dog",), "Meat", "package", "each", None),
    ("Deli Turkey", ("deli meat", "deli ham", "sliced turkey"), "Meat", "pound", "ounce", 16),
    ("Chicken Wings", ("wings",), "Meat", "pound", "pound", None),
    ("Chicken Drumsticks", ("drumsticks",), "Meat", "pound", "pound", None),
    ("Chicken Tenders", ("chicken tenderloins",), "Meat", "pound", "pound", None),
    ("Chicken Legs", (), "Meat", "pound", "pound", None),
    ("Rotisserie Chicken", (), "Meat", "each", "each", None),
    ("Ground Lamb", (), "Meat", "pound", "pound", None),
    ("Beef Brisket", ("brisket",), "Meat", "pound", "pound", None),
    ("Corned Beef", (), "Meat", "pound", "pound", None),
    ("Flank Steak", (), "Meat", "pound", "pound", None),
    ("Skirt Steak", (), "Meat", "pound", "pound", None),
    ("Beef Short Ribs", ("short ribs",), "Meat", "pound", "pound", None),
    ("Beef Tenderloin", ("filet mignon",), "Meat", "pound", "pound", None),
    ("Pork Ribs", ("baby back ribs", "spare ribs"), "Meat", "pound", "pound", None),
    ("Pork Belly", (), "Meat", "pound", "pound", None),
    ("Pork Shoulder", ("pork butt",), "Meat", "pound", "pound", None),
    ("Prosciutto", (), "Meat", "package", "ounce", None),
    ("Salami", (), "Meat", "package", "ounce", None),
    ("Pepperoni", (), "Meat", "package", "ounce", None),
    ("Chorizo", (), "Meat", "pound", "pound", None),
    ("Bratwurst", (), "Meat", "package", "each", None),
    ("Ground Venison", (), "Meat", "pound", "pound", None),
    ("Duck", ("duck breast",), "Meat", "pound", "pound", None),
    # ------------------------------------------------------------------
    # Seafood
    # ------------------------------------------------------------------
    ("Shrimp", (), "Seafood", "pound", "pound", None),
    ("Salmon", ("salmon fillet",), "Seafood", "pound", "pound", None),
    ("Tilapia", (), "Seafood", "pound", "pound", None),
    ("Cod", ("cod fillet",), "Seafood", "pound", "pound", None),
    ("Fresh Tuna", ("tuna steak",), "Seafood", "pound", "pound", None),
    ("Canned Tuna", ("tuna", "canned tuna fish"), "Canned Goods", "can", "can", None),
    ("Crab Meat", ("crab",), "Seafood", "pound", "pound", None),
    ("Scallops", (), "Seafood", "pound", "pound", None),
    ("Lobster", ("lobster tail",), "Seafood", "pound", "pound", None),
    ("Mussels", (), "Seafood", "pound", "pound", None),
    ("Clams", (), "Seafood", "pound", "pound", None),
    ("Catfish", (), "Seafood", "pound", "pound", None),
    ("Halibut", (), "Seafood", "pound", "pound", None),
    ("Mahi Mahi", (), "Seafood", "pound", "pound", None),
    ("Swordfish", (), "Seafood", "pound", "pound", None),
    ("Sardines", ("canned sardines",), "Canned Goods", "can", "can", None),
    ("Anchovies", ("anchovy fillets",), "Canned Goods", "can", "can", None),
    ("Oysters", (), "Seafood", "pound", "each", None),
    ("Crawfish", (), "Seafood", "pound", "pound", None),
    ("Imitation Crab", ("crab sticks",), "Seafood", "pound", "pound", None),
    ("Smoked Salmon", ("lox",), "Seafood", "package", "ounce", None),
    ("Fish Sticks", (), "Frozen", "box", "each", None),
    # ------------------------------------------------------------------
    # Bakery
    # ------------------------------------------------------------------
    ("Sandwich Bread", ("bread", "white bread", "wheat bread", "loaf of bread"), "Bakery", "loaf", "slice", 20),
    ("Bagels", ("bagel",), "Bakery", "package", "each", None),
    ("Flour Tortillas", ("tortillas", "tortilla"), "Bakery", "package", "each", None),
    ("Hamburger Buns", ("burger buns",), "Bakery", "package", "each", None),
    ("Hot Dog Buns", (), "Bakery", "package", "each", None),
    ("Dinner Rolls", (), "Bakery", "package", "each", None),
    ("English Muffins", (), "Bakery", "package", "each", None),
    ("Pita Bread", ("pita",), "Bakery", "package", "each", None),
    ("Croissants", ("croissant",), "Bakery", "package", "each", None),
    ("Baguette", (), "Bakery", "each", "each", None),
    ("Naan", (), "Bakery", "package", "each", None),
    ("Sourdough Bread", (), "Bakery", "loaf", "slice", 20),
    ("Rye Bread", (), "Bakery", "loaf", "slice", 20),
    ("Sub Rolls", ("hoagie rolls",), "Bakery", "package", "each", None),
    ("Pizza Crust", (), "Bakery", "each", "each", None),
    ("Muffins", ("blueberry muffins",), "Bakery", "package", "each", None),
    ("Donuts", ("doughnuts",), "Bakery", "box", "each", None),
    ("Cookies", (), "Bakery", "package", "each", None),
    ("Cupcakes", (), "Bakery", "package", "each", None),
    ("Refrigerated Biscuits", ("canned biscuits",), "Bakery", "can", "each", None),
    ("Crescent Rolls", ("refrigerated crescent rolls",), "Bakery", "can", "each", None),
    ("Pound Cake", (), "Bakery", "each", "each", None),
    ("Angel Food Cake", (), "Bakery", "each", "each", None),
    ("Pie Shell", (), "Bakery", "each", "each", None),
    ("Breadsticks", (), "Bakery", "package", "each", None),
    # ------------------------------------------------------------------
    # Pantry - grains & pasta
    # ------------------------------------------------------------------
    ("White Rice", ("rice", "long grain rice", "long grain white rice"), "Pantry", "pound", "cup", 2.4),
    ("Brown Rice", (), "Pantry", "pound", "cup", 2.2),
    ("Jasmine Rice", (), "Pantry", "pound", "cup", 2.4),
    ("Basmati Rice", (), "Pantry", "pound", "cup", 2.4),
    ("Quinoa", (), "Pantry", "pound", "cup", 2.4),
    ("Spaghetti", ("spaghetti noodles",), "Pantry", "pound", "pound", None),
    ("Penne Pasta", ("penne",), "Pantry", "pound", "pound", None),
    ("Macaroni", ("elbow macaroni",), "Pantry", "pound", "pound", None),
    ("Egg Noodles", (), "Pantry", "each", "each", None),
    ("Lasagna Noodles", (), "Pantry", "each", "each", None),
    ("Couscous", (), "Pantry", "each", "cup", None),
    ("Rolled Oats", ("oats", "old fashioned oats"), "Pantry", "pound", "cup", 5.0),
    ("Steel Cut Oats", (), "Pantry", "each", "cup", None),
    ("Cornmeal", (), "Pantry", "each", "cup", None),
    ("Breadcrumbs", ("bread crumbs",), "Pantry", "each", "cup", None),
    ("Panko Breadcrumbs", ("panko",), "Pantry", "each", "cup", None),
    ("Bulgur", (), "Pantry", "pound", "cup", None),
    ("Farro", (), "Pantry", "pound", "cup", None),
    ("Pearl Barley", ("barley",), "Pantry", "pound", "cup", None),
    ("Orzo", (), "Pantry", "pound", "pound", None),
    ("Fettuccine", (), "Pantry", "pound", "pound", None),
    ("Linguine", (), "Pantry", "pound", "pound", None),
    ("Angel Hair Pasta", (), "Pantry", "pound", "pound", None),
    ("Farfalle Pasta", ("bowtie pasta",), "Pantry", "pound", "pound", None),
    ("Rigatoni", (), "Pantry", "pound", "pound", None),
    ("Ziti", (), "Pantry", "pound", "pound", None),
    ("Ramen Noodles", (), "Pantry", "package", "each", None),
    ("Rice Noodles", (), "Pantry", "each", "each", None),
    ("Grits", (), "Pantry", "each", "cup", None),
    ("Polenta", (), "Pantry", "each", "cup", None),
    ("Wild Rice", (), "Pantry", "pound", "cup", None),
    ("Arborio Rice", (), "Pantry", "pound", "cup", 2.4),
    ("Sushi Rice", (), "Pantry", "pound", "cup", 2.4),
    # ------------------------------------------------------------------
    # Baking
    # ------------------------------------------------------------------
    ("All-Purpose Flour", ("flour", "ap flour", "plain flour"), "Baking", "pound", "cup", 3.78),
    ("Whole Wheat Flour", (), "Baking", "pound", "pound", None),
    ("Bread Flour", (), "Baking", "pound", "pound", None),
    ("Cake Flour", (), "Baking", "pound", "pound", None),
    ("Granulated Sugar", ("sugar", "white sugar"), "Baking", "pound", "cup", 2.27),
    ("Brown Sugar", ("light brown sugar", "dark brown sugar"), "Baking", "pound", "pound", None),
    ("Powdered Sugar", ("confectioners sugar", "icing sugar"), "Baking", "pound", "pound", None),
    ("Baking Powder", (), "Baking", "each", "teaspoon", None),
    ("Baking Soda", ("sodium bicarbonate",), "Baking", "each", "teaspoon", None),
    ("Table Salt", ("salt",), "Baking", "each", "teaspoon", None),
    ("Kosher Salt", (), "Baking", "each", "teaspoon", None),
    ("Active Dry Yeast", ("yeast",), "Baking", "each", "teaspoon", None),
    ("Vanilla Extract", ("vanilla",), "Baking", "each", "teaspoon", None),
    ("Cocoa Powder", ("unsweetened cocoa powder", "cocoa"), "Baking", "each", "cup", None),
    ("Chocolate Chips", ("semi sweet chocolate chips",), "Baking", "each", "cup", None),
    ("Cornstarch", (), "Baking", "each", "tablespoon", None),
    ("Honey", (), "Baking", "each", "tablespoon", None),
    ("Maple Syrup", (), "Baking", "each", "tablespoon", None),
    ("Molasses", (), "Baking", "each", "tablespoon", None),
    ("Sweetened Condensed Milk", (), "Baking", "can", "can", None),
    ("Evaporated Milk", (), "Baking", "can", "can", None),
    ("Food Coloring", (), "Baking", "each", "drop", None),
    ("Sprinkles", (), "Baking", "each", "tablespoon", None),
    ("Graham Cracker Crumbs", (), "Baking", "each", "cup", None),
    ("Shortening", ("vegetable shortening",), "Baking", "each", "cup", None),
    ("Almond Flour", (), "Baking", "each", "cup", None),
    ("Yeast Packets", ("instant yeast",), "Baking", "each", "teaspoon", None),
    ("Cream of Tartar", (), "Baking", "each", "teaspoon", None),
    ("Almond Extract", (), "Baking", "each", "teaspoon", None),
    ("Lemon Extract", (), "Baking", "each", "teaspoon", None),
    ("Peppermint Extract", (), "Baking", "each", "teaspoon", None),
    ("Marshmallows", ("mini marshmallows",), "Baking", "bag", "cup", None),
    ("Marshmallow Fluff", (), "Baking", "each", "cup", None),
    ("Pudding Mix", ("instant pudding",), "Baking", "box", "box", None),
    ("Gelatin Dessert Mix", ("jello",), "Baking", "box", "box", None),
    ("Cake Mix", (), "Baking", "box", "box", None),
    ("Brownie Mix", (), "Baking", "box", "box", None),
    ("Pancake Mix", (), "Baking", "box", "cup", None),
    ("Waffle Mix", (), "Baking", "box", "cup", None),
    ("Cornbread Mix", (), "Baking", "box", "box", None),
    ("Sweetened Shredded Coconut", (), "Baking", "each", "cup", None),
    ("Dark Chocolate Chips", (), "Baking", "each", "cup", None),
    ("White Chocolate Chips", (), "Baking", "each", "cup", None),
    ("Baking Chocolate", ("unsweetened chocolate", "bakers chocolate"), "Baking", "each", "ounce", None),
    ("Almond Meal", (), "Baking", "each", "cup", None),
    ("Coconut Sugar", (), "Baking", "pound", "pound", None),
    ("Turbinado Sugar", ("raw sugar",), "Baking", "pound", "pound", None),
    # ------------------------------------------------------------------
    # Canned & jarred
    # ------------------------------------------------------------------
    ("Canned Black Beans", ("black beans",), "Canned Goods", "can", "can", None),
    ("Canned Kidney Beans", ("kidney beans",), "Canned Goods", "can", "can", None),
    ("Canned Pinto Beans", ("pinto beans",), "Canned Goods", "can", "can", None),
    ("Canned Chickpeas", ("chickpeas", "garbanzo beans"), "Canned Goods", "can", "can", None),
    ("Canned Diced Tomatoes", ("diced tomatoes",), "Canned Goods", "can", "can", None),
    ("Canned Crushed Tomatoes", ("crushed tomatoes",), "Canned Goods", "can", "can", None),
    ("Canned Tomato Sauce", ("tomato sauce",), "Canned Goods", "can", "can", None),
    ("Tomato Paste", (), "Canned Goods", "can", "tablespoon", None),
    ("Canned Corn", (), "Canned Goods", "can", "can", None),
    ("Canned Green Beans", (), "Canned Goods", "can", "can", None),
    ("Chicken Broth", ("chicken stock",), "Canned Goods", "quart", "cup", 4),
    ("Beef Broth", ("beef stock",), "Canned Goods", "quart", "cup", 4),
    ("Vegetable Broth", ("vegetable stock",), "Canned Goods", "quart", "cup", 4),
    ("Canned Coconut Milk", ("coconut milk",), "Canned Goods", "can", "can", None),
    ("Canned Pumpkin Puree", ("pumpkin puree",), "Canned Goods", "can", "can", None),
    ("Pickles", ("dill pickles",), "Condiments", "jar", "jar", None),
    ("Olives", ("black olives", "green olives"), "Condiments", "jar", "cup", None),
    ("Salsa", (), "Condiments", "jar", "cup", None),
    ("Marinara Sauce", ("pasta sauce", "spaghetti sauce"), "Condiments", "jar", "cup", None),
    ("Alfredo Sauce", (), "Condiments", "jar", "cup", None),
    ("Peanut Butter", (), "Pantry", "each", "tablespoon", None),
    ("Jam", ("jelly", "preserves"), "Pantry", "each", "tablespoon", None),
    ("Applesauce", (), "Pantry", "each", "cup", None),
    ("Canned Peaches", ("canned fruit",), "Canned Goods", "can", "can", None),
    ("Canned Mandarin Oranges", (), "Canned Goods", "can", "can", None),
    ("Canned Mushrooms", (), "Canned Goods", "can", "can", None),
    ("Canned Beets", (), "Canned Goods", "can", "can", None),
    ("Canned Sweet Potatoes", ("canned yams",), "Canned Goods", "can", "can", None),
    ("Canned Spinach", (), "Canned Goods", "can", "can", None),
    ("Canned Asparagus", (), "Canned Goods", "can", "can", None),
    ("Roasted Red Peppers", (), "Condiments", "jar", "cup", None),
    ("Sun-Dried Tomatoes", (), "Condiments", "jar", "cup", None),
    ("Capers", (), "Condiments", "jar", "tablespoon", None),
    ("Canned Chili", (), "Canned Goods", "can", "can", None),
    ("Cream of Mushroom Soup", (), "Canned Goods", "can", "can", None),
    ("Cream of Chicken Soup", (), "Canned Goods", "can", "can", None),
    ("Tomato Soup", (), "Canned Goods", "can", "can", None),
    ("Refried Beans", (), "Canned Goods", "can", "can", None),
    ("Canned Black-Eyed Peas", (), "Canned Goods", "can", "can", None),
    ("Canned Great Northern Beans", (), "Canned Goods", "can", "can", None),
    ("Canned Cannellini Beans", ("white beans",), "Canned Goods", "can", "can", None),
    ("Canned Lentils", (), "Canned Goods", "can", "can", None),
    ("Fruit Cocktail", (), "Canned Goods", "can", "can", None),
    ("Canned Pineapple", (), "Canned Goods", "can", "can", None),
    ("Marinated Artichoke Hearts", ("artichoke hearts",), "Condiments", "jar", "cup", None),
    ("Chipotle Peppers in Adobo", ("chipotles in adobo",), "Condiments", "can", "each", None),
    # ------------------------------------------------------------------
    # Condiments & sauces
    # ------------------------------------------------------------------
    ("Ketchup", (), "Condiments", "each", "tablespoon", None),
    ("Mustard", ("yellow mustard", "dijon mustard"), "Condiments", "each", "tablespoon", None),
    ("Mayonnaise", ("mayo",), "Condiments", "each", "tablespoon", None),
    ("Soy Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Worcestershire Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Hot Sauce", (), "Condiments", "each", "teaspoon", None),
    ("BBQ Sauce", ("barbecue sauce",), "Condiments", "each", "tablespoon", None),
    ("Ranch Dressing", (), "Condiments", "each", "tablespoon", None),
    ("Italian Dressing", (), "Condiments", "each", "tablespoon", None),
    ("Balsamic Vinegar", (), "Condiments", "each", "tablespoon", None),
    ("Apple Cider Vinegar", (), "Condiments", "each", "tablespoon", None),
    ("White Vinegar", (), "Condiments", "each", "tablespoon", None),
    ("Rice Vinegar", (), "Condiments", "each", "tablespoon", None),
    ("Olive Oil", (), "Condiments", "quart", "tablespoon", 64),
    ("Vegetable Oil", (), "Condiments", "quart", "tablespoon", 64),
    ("Canola Oil", (), "Condiments", "quart", "tablespoon", 64),
    ("Sesame Oil", (), "Condiments", "each", "tablespoon", None),
    ("Coconut Oil", (), "Condiments", "each", "tablespoon", None),
    ("Cooking Spray", (), "Condiments", "each", "each", None),
    ("Sriracha", (), "Condiments", "each", "teaspoon", None),
    ("Teriyaki Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Fish Sauce", (), "Condiments", "each", "teaspoon", None),
    ("Oyster Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Hoisin Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Tahini", (), "Condiments", "each", "tablespoon", None),
    ("Salad Dressing", (), "Condiments", "each", "tablespoon", None),
    ("Steak Sauce", ("a1", "a1 sauce"), "Condiments", "each", "tablespoon", None),
    ("Cocktail Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Tartar Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Prepared Horseradish", (), "Condiments", "each", "teaspoon", None),
    ("Chili Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Enchilada Sauce", (), "Condiments", "can", "cup", None),
    ("Pizza Sauce", (), "Condiments", "jar", "cup", None),
    ("Pesto", (), "Condiments", "jar", "tablespoon", None),
    ("Vinaigrette", (), "Condiments", "each", "tablespoon", None),
    ("Miso Paste", ("miso",), "Condiments", "each", "tablespoon", None),
    ("Curry Paste", ("red curry paste", "green curry paste"), "Condiments", "each", "tablespoon", None),
    ("Sambal Oelek", (), "Condiments", "each", "teaspoon", None),
    ("Gochujang", (), "Condiments", "each", "tablespoon", None),
    ("Wasabi", (), "Condiments", "each", "teaspoon", None),
    ("Avocado Oil", (), "Condiments", "each", "tablespoon", None),
    ("Peanut Oil", (), "Condiments", "each", "tablespoon", None),
    ("Buffalo Sauce", (), "Condiments", "each", "tablespoon", None),
    ("Caesar Dressing", (), "Condiments", "each", "tablespoon", None),
    ("Honey Mustard", (), "Condiments", "each", "tablespoon", None),
    # ------------------------------------------------------------------
    # Spices & seasonings
    # ------------------------------------------------------------------
    ("Black Pepper", ("ground black pepper", "pepper"), "Spices", "each", "teaspoon", None),
    ("Garlic Powder", (), "Spices", "each", "teaspoon", None),
    ("Onion Powder", (), "Spices", "each", "teaspoon", None),
    ("Paprika", (), "Spices", "each", "teaspoon", None),
    ("Smoked Paprika", (), "Spices", "each", "teaspoon", None),
    ("Ground Cumin", ("cumin",), "Spices", "each", "teaspoon", None),
    ("Chili Powder", (), "Spices", "each", "teaspoon", None),
    ("Cayenne Pepper", (), "Spices", "each", "teaspoon", None),
    ("Red Pepper Flakes", ("crushed red pepper",), "Spices", "each", "teaspoon", None),
    ("Italian Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Dried Oregano", ("oregano",), "Spices", "each", "teaspoon", None),
    ("Dried Basil", (), "Spices", "each", "teaspoon", None),
    ("Dried Thyme", (), "Spices", "each", "teaspoon", None),
    ("Dried Rosemary", (), "Spices", "each", "teaspoon", None),
    ("Bay Leaves", ("bay leaf",), "Spices", "each", "each", None),
    ("Ground Cinnamon", ("cinnamon",), "Spices", "each", "teaspoon", None),
    ("Nutmeg", ("ground nutmeg",), "Spices", "each", "teaspoon", None),
    ("Ground Ginger", (), "Spices", "each", "teaspoon", None),
    ("Allspice", (), "Spices", "each", "teaspoon", None),
    ("Ground Cloves", ("cloves",), "Spices", "each", "teaspoon", None),
    ("Curry Powder", (), "Spices", "each", "teaspoon", None),
    ("Turmeric", ("ground turmeric",), "Spices", "each", "teaspoon", None),
    ("Garam Masala", (), "Spices", "each", "teaspoon", None),
    ("Taco Seasoning", (), "Spices", "each", "tablespoon", None),
    ("Ranch Seasoning Mix", (), "Spices", "each", "tablespoon", None),
    ("Everything Bagel Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Celery Seed", (), "Spices", "each", "teaspoon", None),
    ("Mustard Powder", ("dry mustard",), "Spices", "each", "teaspoon", None),
    ("Ground Coriander", ("coriander",), "Spices", "each", "teaspoon", None),
    ("Fennel Seed", (), "Spices", "each", "teaspoon", None),
    ("Sesame Seeds", (), "Spices", "each", "tablespoon", None),
    ("Poppy Seeds", (), "Spices", "each", "tablespoon", None),
    ("Sea Salt", (), "Spices", "each", "teaspoon", None),
    ("Dried Parsley", (), "Spices", "each", "teaspoon", None),
    ("Lemon Pepper", (), "Spices", "each", "teaspoon", None),
    ("Chinese Five Spice", ("five spice powder",), "Spices", "each", "teaspoon", None),
    ("White Pepper", (), "Spices", "each", "teaspoon", None),
    ("Cardamom", ("ground cardamom",), "Spices", "each", "teaspoon", None),
    ("Star Anise", (), "Spices", "each", "each", None),
    ("Saffron", (), "Spices", "each", "teaspoon", None),
    ("Sumac", (), "Spices", "each", "teaspoon", None),
    ("Za'atar", (), "Spices", "each", "teaspoon", None),
    ("Herbes de Provence", (), "Spices", "each", "teaspoon", None),
    ("Old Bay Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Cajun Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Poultry Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Pumpkin Pie Spice", (), "Spices", "each", "teaspoon", None),
    ("Adobo Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Seasoned Salt", ("seasoning salt",), "Spices", "each", "teaspoon", None),
    ("Onion Salt", (), "Spices", "each", "teaspoon", None),
    ("Garlic Salt", (), "Spices", "each", "teaspoon", None),
    ("Meat Tenderizer", (), "Spices", "each", "teaspoon", None),
    ("Dill Seed", (), "Spices", "each", "teaspoon", None),
    ("Caraway Seed", (), "Spices", "each", "teaspoon", None),
    ("Vanilla Bean", ("vanilla beans",), "Spices", "each", "each", None),
    ("Whole Cloves", (), "Spices", "each", "teaspoon", None),
    ("Whole Black Peppercorns", ("peppercorns",), "Spices", "each", "teaspoon", None),
    ("Dried Minced Onion", ("minced onion", "dried onion flakes", "onion flakes", "dehydrated onion"), "Spices", "each", "teaspoon", None),
    ("Dried Minced Garlic", ("minced garlic flakes", "garlic flakes", "dehydrated garlic", "granulated garlic"), "Spices", "each", "teaspoon", None),
    ("Dried Chives", (), "Spices", "each", "teaspoon", None),
    ("Dried Sage", ("rubbed sage",), "Spices", "each", "teaspoon", None),
    ("Dried Tarragon", (), "Spices", "each", "teaspoon", None),
    ("Dried Marjoram", (), "Spices", "each", "teaspoon", None),
    ("Dried Dill Weed", ("dill weed",), "Spices", "each", "teaspoon", None),
    ("Ground Mustard Seed", (), "Spices", "each", "teaspoon", None),
    ("Anise Seed", (), "Spices", "each", "teaspoon", None),
    ("Juniper Berries", (), "Spices", "each", "teaspoon", None),
    ("Whole Nutmeg", (), "Spices", "each", "each", None),
    ("Steak Seasoning", ("montreal steak seasoning",), "Spices", "each", "teaspoon", None),
    ("Chicken Bouillon", ("chicken bouillon cubes", "chicken bouillon granules"), "Spices", "each", "cube", None),
    ("Beef Bouillon", ("beef bouillon cubes", "beef bouillon granules"), "Spices", "each", "cube", None),
    ("Vegetable Bouillon", ("vegetable bouillon cubes",), "Spices", "each", "cube", None),
    ("MSG", ("monosodium glutamate", "accent seasoning"), "Spices", "each", "teaspoon", None),
    ("Chili Lime Seasoning", ("tajin",), "Spices", "each", "teaspoon", None),
    ("Jerk Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Blackened Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Grill Seasoning", (), "Spices", "each", "teaspoon", None),
    ("Pickling Spice", (), "Spices", "each", "teaspoon", None),
    ("Apple Pie Spice", (), "Spices", "each", "teaspoon", None),
    # ------------------------------------------------------------------
    # Snacks
    # ------------------------------------------------------------------
    ("Potato Chips", ("chips",), "Snacks", "bag", "cup", None),
    ("Tortilla Chips", (), "Snacks", "bag", "cup", None),
    ("Pretzels", (), "Snacks", "bag", "cup", None),
    ("Popcorn", (), "Snacks", "bag", "cup", None),
    ("Crackers", (), "Snacks", "box", "each", None),
    ("Granola Bars", ("granola bar",), "Snacks", "box", "each", None),
    ("Trail Mix", (), "Snacks", "bag", "cup", None),
    ("Peanuts", (), "Snacks", "bag", "cup", None),
    ("Almonds", (), "Snacks", "bag", "cup", None),
    ("Walnuts", (), "Snacks", "bag", "cup", None),
    ("Cashews", (), "Snacks", "bag", "cup", None),
    ("Pecans", (), "Snacks", "bag", "cup", None),
    ("Sunflower Seeds", (), "Snacks", "bag", "cup", None),
    ("Raisins", (), "Snacks", "box", "cup", None),
    ("Dried Cranberries", ("craisins",), "Snacks", "bag", "cup", None),
    ("Rice Cakes", (), "Snacks", "package", "each", None),
    ("Fruit Snacks", (), "Snacks", "box", "each", None),
    ("Beef Jerky", (), "Snacks", "bag", "ounce", None),
    ("Pistachios", (), "Snacks", "bag", "cup", None),
    ("Macadamia Nuts", (), "Snacks", "bag", "cup", None),
    ("Hazelnuts", (), "Snacks", "bag", "cup", None),
    ("Pine Nuts", (), "Snacks", "bag", "cup", None),
    ("Dried Apricots", (), "Snacks", "bag", "cup", None),
    ("Dried Mango", (), "Snacks", "bag", "cup", None),
    ("Cereal Bars", (), "Snacks", "box", "each", None),
    ("Graham Crackers", (), "Snacks", "box", "each", None),
    ("Animal Crackers", (), "Snacks", "box", "cup", None),
    ("Corn Nuts", (), "Snacks", "bag", "cup", None),
    ("Cheese Crackers", (), "Snacks", "box", "cup", None),
    ("Pudding Cups", (), "Snacks", "package", "each", None),
    # ------------------------------------------------------------------
    # Beverages
    # ------------------------------------------------------------------
    ("Coffee", ("ground coffee", "coffee beans"), "Beverages", "bag", "tablespoon", None),
    ("Tea", ("tea bags",), "Beverages", "box", "each", None),
    ("Orange Juice", (), "Beverages", "gallon", "cup", 16),
    ("Apple Juice", (), "Beverages", "gallon", "cup", 16),
    ("Soda", ("pop", "soft drink"), "Beverages", "each", "each", None),
    ("Sparkling Water", (), "Beverages", "each", "each", None),
    ("Bottled Water", (), "Beverages", "each", "each", None),
    ("Cooking Wine", ("white wine", "red wine"), "Beverages", "bottle", "cup", None),
    ("Beer", (), "Beverages", "each", "each", None),
    ("Lemonade", (), "Beverages", "each", "cup", None),
    ("Sports Drink", (), "Beverages", "each", "each", None),
    ("Almond Milk", (), "Beverages", "each", "cup", None),
    ("Oat Milk", (), "Beverages", "each", "cup", None),
    ("Soy Milk", (), "Beverages", "each", "cup", None),
    ("Coconut Water", (), "Beverages", "each", "cup", None),
    ("Energy Drink", (), "Beverages", "each", "each", None),
    ("Kombucha", (), "Beverages", "each", "cup", None),
    ("Hot Chocolate Mix", ("cocoa mix",), "Beverages", "box", "each", None),
    ("Powdered Drink Mix", ("kool-aid",), "Beverages", "each", "each", None),
    ("Cranberry Juice", (), "Beverages", "each", "cup", None),
    ("Grape Juice", (), "Beverages", "each", "cup", None),
    ("Pineapple Juice", (), "Beverages", "each", "cup", None),
    ("Tomato Juice", (), "Beverages", "each", "cup", None),
    ("Club Soda", (), "Beverages", "each", "each", None),
    ("Tonic Water", (), "Beverages", "each", "each", None),
    ("Ginger Ale", (), "Beverages", "each", "each", None),
    ("Root Beer", (), "Beverages", "each", "each", None),
    ("Dry Sherry", ("cooking sherry",), "Beverages", "bottle", "tablespoon", None),
    ("Marsala Wine", (), "Beverages", "bottle", "cup", None),
    ("Champagne", ("sparkling wine",), "Beverages", "bottle", "cup", None),
    # ------------------------------------------------------------------
    # Flavoring syrups - Torani (88-flavor "Original Syrups" line - see
    # https://www.torani.com/products/original-syrups.html; a handful of
    # very-limited-run or seasonal flavors not consistently listed there
    # are omitted rather than guessed at) and Dopoco (powder-concentrate
    # syrups - see https://dopoco.com/collections/all, "Classic Flavors").
    # All left at purchase_unit "each" (a bottle/packet) with stock_unit
    # "tablespoon", matching how Honey and Maple Syrup are handled above -
    # no invented bottle-to-tablespoon factor since bottle sizes vary by
    # flavor and edition.
    # ------------------------------------------------------------------
    ("Torani Cookie Butter Syrup", ("cookie butter syrup", "torani cookie butter"), "Syrups", "each", "tablespoon", None),
    ("Torani Blue Raspberry Syrup", ("blue raspberry syrup", "torani blue raspberry"), "Syrups", "each", "tablespoon", None),
    ("Torani Vanilla Syrup", ("vanilla syrup", "torani vanilla"), "Syrups", "each", "tablespoon", None),
    ("Torani Pumpkin Spice Syrup", ("pumpkin spice syrup", "torani pumpkin spice"), "Syrups", "each", "tablespoon", None),
    ("Torani Raspberry Syrup", ("raspberry syrup", "torani raspberry"), "Syrups", "each", "tablespoon", None),
    ("Torani Crème de Banana Syrup", ("creme de banana syrup", "banana syrup"), "Syrups", "each", "tablespoon", None),
    ("Torani Pumpkin Pie Syrup", ("pumpkin pie syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani French Vanilla Syrup", ("french vanilla syrup", "torani french vanilla"), "Syrups", "each", "tablespoon", None),
    ("Torani Grenadine Syrup", ("grenadine", "torani grenadine"), "Syrups", "each", "tablespoon", None),
    ("Torani Lavender Syrup", ("lavender syrup", "torani lavender"), "Syrups", "each", "tablespoon", None),
    ("Torani Chocolate Milano Syrup", ("chocolate milano syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Classic Hazelnut Syrup", ("hazelnut syrup", "torani hazelnut"), "Syrups", "each", "tablespoon", None),
    ("Torani Tiramisu Syrup", ("tiramisu syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Almond (Orgeat) Syrup", ("orgeat syrup", "almond syrup", "torani almond"), "Syrups", "each", "tablespoon", None),
    ("Torani Salted Honey Butter Syrup", ("salted honey butter syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Chai Tea Spice Syrup", ("chai tea spice syrup", "chai syrup"), "Syrups", "each", "tablespoon", None),
    ("Torani Irish Cream Syrup", ("irish cream syrup", "torani irish cream"), "Syrups", "each", "tablespoon", None),
    ("Torani Shortbread Syrup", ("shortbread syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Amaretto Syrup", ("amaretto syrup", "torani amaretto"), "Syrups", "each", "tablespoon", None),
    ("Torani Blue Curacao Syrup", ("blue curacao syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Cinnamon Syrup", ("cinnamon syrup", "torani cinnamon"), "Syrups", "each", "tablespoon", None),
    ("Torani Macadamia Nut Syrup", ("macadamia nut syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Lychee Syrup", ("lychee syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Cane Sweetener Syrup", ("cane sweetener syrup", "cane syrup"), "Syrups", "each", "tablespoon", None),
    ("Torani Almond Roca Syrup", ("almond roca syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Mojito Mint Syrup", ("mojito mint syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Classic Root Beer Syrup", ("root beer syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Rose Syrup", ("rose syrup", "torani rose"), "Syrups", "each", "tablespoon", None),
    ("Torani Crème Caramel Syrup", ("creme caramel syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Crème de Menthe Syrup", ("creme de menthe syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Ruby Red Grapefruit Syrup", ("ruby red grapefruit syrup", "grapefruit syrup"), "Syrups", "each", "tablespoon", None),
    ("Torani Tamarindo Syrup", ("tamarindo syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Black Anisette Syrup", ("black anisette syrup", "anisette syrup"), "Syrups", "each", "tablespoon", None),
    ("Torani Diamond Syrup", (), "Syrups", "each", "tablespoon", None),
    ("Torani Butter Pecan Syrup", ("butter pecan syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Classic Caramel Syrup", ("caramel syrup", "torani caramel"), "Syrups", "each", "tablespoon", None),
    ("Torani Peach Syrup", ("peach syrup", "torani peach"), "Syrups", "each", "tablespoon", None),
    ("Torani Strawberry Syrup", ("strawberry syrup", "torani strawberry"), "Syrups", "each", "tablespoon", None),
    ("Torani Salted Caramel Syrup", ("salted caramel syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Peppermint Syrup", ("peppermint syrup", "torani peppermint"), "Syrups", "each", "tablespoon", None),
    ("Torani Pistachio Syrup", ("pistachio syrup", "torani pistachio"), "Syrups", "each", "tablespoon", None),
    ("Torani Brown Sugar Syrup", ("brown sugar syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani White Peach Syrup", ("white peach syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Cherry Lime Syrup", ("cherry lime syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Chocolate Chip Cookie Dough Syrup", ("chocolate chip cookie dough syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Bourbon Caramel Syrup", ("bourbon caramel syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Apple Syrup", ("apple syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Blackberry Syrup", ("blackberry syrup", "torani blackberry"), "Syrups", "each", "tablespoon", None),
    ("Torani Brown Sugar Cinnamon Syrup", ("brown sugar cinnamon syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Blood Orange Syrup", ("blood orange syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Blueberry Syrup", ("blueberry syrup", "torani blueberry"), "Syrups", "each", "tablespoon", None),
    ("Torani Butterscotch Syrup", ("butterscotch syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Caramel Syrup", (), "Syrups", "each", "tablespoon", None),
    ("Torani Cherry Syrup", ("cherry syrup", "torani cherry"), "Syrups", "each", "tablespoon", None),
    ("Torani Cheesecake Syrup", ("cheesecake syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani White Chocolate Syrup", ("white chocolate syrup", "chocolate bianco syrup"), "Syrups", "each", "tablespoon", None),
    ("Torani Cantaloupe Syrup", ("cantaloupe syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Coconut Syrup", ("coconut syrup", "torani coconut"), "Syrups", "each", "tablespoon", None),
    ("Torani Grape Syrup", ("grape syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Green Apple Syrup", ("green apple syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Guava Syrup", ("guava syrup", "torani guava"), "Syrups", "each", "tablespoon", None),
    ("Torani Hazelnut Syrup", (), "Syrups", "each", "tablespoon", None),
    ("Torani Huckleberry Syrup", ("huckleberry syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Kiwi Syrup", ("kiwi syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Lemon Syrup", ("lemon syrup", "torani lemon"), "Syrups", "each", "tablespoon", None),
    ("Torani Lime Syrup", ("lime syrup", "torani lime"), "Syrups", "each", "tablespoon", None),
    ("Torani Mango Syrup", ("mango syrup", "torani mango"), "Syrups", "each", "tablespoon", None),
    ("Torani Maple Flavor Syrup", ("maple flavor syrup", "torani maple"), "Syrups", "each", "tablespoon", None),
    ("Torani Orange Syrup", ("orange syrup", "torani orange"), "Syrups", "each", "tablespoon", None),
    ("Torani Passion Fruit Syrup", ("passion fruit syrup", "torani passion fruit"), "Syrups", "each", "tablespoon", None),
    ("Torani Pineapple Syrup", ("pineapple syrup", "torani pineapple"), "Syrups", "each", "tablespoon", None),
    ("Torani Pomegranate Syrup", ("pomegranate syrup", "torani pomegranate"), "Syrups", "each", "tablespoon", None),
    ("Torani Red Raspberry Syrup", ("red raspberry syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani English Toffee Syrup", ("english toffee syrup", "toffee syrup"), "Syrups", "each", "tablespoon", None),
    ("Torani Vanilla Bean Syrup", ("vanilla bean syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Toasted Marshmallow Syrup", ("toasted marshmallow syrup",), "Syrups", "each", "tablespoon", None),
    ("Torani Gingerbread Syrup", ("gingerbread syrup", "torani gingerbread"), "Syrups", "each", "tablespoon", None),
    ("Torani Watermelon Syrup", ("watermelon syrup", "torani watermelon"), "Syrups", "each", "tablespoon", None),
    ("Torani Cupcake Syrup", ("cupcake syrup", "torani cupcake"), "Syrups", "each", "tablespoon", None),
    ("Dopoco Almond Syrup", ("dopoco almond",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Banana Syrup", ("dopoco banana",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Blackberry Syrup", ("dopoco blackberry",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Blue Raspberry Syrup", ("dopoco blue raspberry",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Brown Sugar Cinnamon Syrup", ("dopoco brown sugar cinnamon",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Caramel Syrup", ("dopoco caramel",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Cherry Syrup", ("dopoco cherry",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Chocolate Syrup", ("dopoco chocolate",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Cinnamon Syrup", ("dopoco cinnamon",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Coconut Syrup", ("dopoco coconut",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Cranberry Syrup", ("dopoco cranberry",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Cupcake Syrup", ("dopoco cupcake",), "Syrups", "each", "tablespoon", None),
    ("Dopoco French Vanilla Syrup", ("dopoco french vanilla",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Guava Syrup", ("dopoco guava",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Hazelnut Syrup", ("dopoco hazelnut",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Irish Cream Syrup", ("dopoco irish cream",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Lavender Syrup", ("dopoco lavender",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Lemon Syrup", ("dopoco lemon",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Lime Syrup", ("dopoco lime",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Mango Syrup", ("dopoco mango",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Maple Syrup Flavor", ("dopoco maple",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Orange Syrup", ("dopoco orange",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Passion Fruit Syrup", ("dopoco passion fruit",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Peach Syrup", ("dopoco peach",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Peppermint Syrup", ("dopoco peppermint",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Pineapple Syrup", ("dopoco pineapple",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Pistachio Syrup", ("dopoco pistachio",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Pomegranate Syrup", ("dopoco pomegranate",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Pumpkin Spice Syrup", ("dopoco pumpkin spice",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Raspberry Syrup", ("dopoco raspberry",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Salted Caramel Syrup", ("dopoco salted caramel",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Strawberry Syrup", ("dopoco strawberry",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Toasted Marshmallow Syrup", ("dopoco toasted marshmallow",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Toffee Syrup", ("dopoco toffee",), "Syrups", "each", "tablespoon", None),
    ("Dopoco Vanilla Syrup", ("dopoco vanilla",), "Syrups", "each", "tablespoon", None),
    # ------------------------------------------------------------------
    # Frozen
    # ------------------------------------------------------------------
    ("Frozen Peas", (), "Frozen", "bag", "cup", None),
    ("Frozen Corn", (), "Frozen", "bag", "cup", None),
    ("Frozen Mixed Vegetables", (), "Frozen", "bag", "cup", None),
    ("Frozen Broccoli", (), "Frozen", "bag", "cup", None),
    ("Frozen Berries", ("frozen mixed berries", "frozen strawberries", "frozen blueberries"), "Frozen", "bag", "cup", None),
    ("Frozen Pizza", (), "Frozen", "each", "each", None),
    ("Frozen French Fries", ("french fries", "fries"), "Frozen", "bag", "cup", None),
    ("Ice Cream", (), "Frozen", "each", "cup", None),
    ("Frozen Waffles", (), "Frozen", "box", "each", None),
    ("Frozen Chicken Nuggets", (), "Frozen", "bag", "each", None),
    ("Frozen Shrimp", (), "Frozen", "bag", "pound", None),
    ("Frozen Spinach", (), "Frozen", "package", "cup", None),
    ("Frozen Pie Crust", ("pie crust",), "Frozen", "each", "each", None),
    ("Puff Pastry", (), "Frozen", "package", "sheet", None),
    ("Frozen Bread Dough", ("pizza dough",), "Frozen", "each", "each", None),
    ("Frozen Fish Fillets", (), "Frozen", "bag", "each", None),
    ("Frozen Meatballs", (), "Frozen", "bag", "each", None),
    ("Frozen Burritos", (), "Frozen", "box", "each", None),
    ("Frozen Dumplings", ("potstickers",), "Frozen", "bag", "each", None),
    ("Frozen Edamame", (), "Frozen", "bag", "cup", None),
    ("Frozen Hash Browns", ("hash browns",), "Frozen", "bag", "cup", None),
    ("Frozen Onion Rings", (), "Frozen", "bag", "each", None),
    ("Frozen Tater Tots", ("tater tots",), "Frozen", "bag", "cup", None),
    ("Frozen Breakfast Sandwiches", (), "Frozen", "box", "each", None),
    ("Frozen Garlic Bread", (), "Frozen", "package", "each", None),
    ("Popsicles", (), "Frozen", "box", "each", None),
    ("Sherbet", (), "Frozen", "each", "cup", None),
    # ------------------------------------------------------------------
    # Other / international
    # ------------------------------------------------------------------
    ("Tofu", ("firm tofu", "extra firm tofu"), "Other", "each", "each", None),
    ("Tempeh", (), "Other", "each", "each", None),
    ("Seitan", (), "Other", "each", "each", None),
    ("Kimchi", (), "Other", "jar", "cup", None),
    ("Sauerkraut", (), "Other", "jar", "cup", None),
    ("Wonton Wrappers", (), "Other", "package", "each", None),
    ("Egg Roll Wrappers", (), "Other", "package", "each", None),
    ("Nutritional Yeast", (), "Other", "each", "tablespoon", None),
    ("Coconut Flakes", ("shredded coconut",), "Other", "each", "cup", None),
    ("Gelatin", ("unflavored gelatin",), "Other", "each", "teaspoon", None),
    ("Rice Paper Wrappers", (), "Other", "package", "each", None),
    ("Nori Sheets", ("seaweed sheets",), "Other", "package", "each", None),
    ("Coconut Cream", (), "Other", "can", "cup", None),
    ("Tamarind Paste", (), "Other", "each", "tablespoon", None),
    ("Harissa", (), "Other", "jar", "tablespoon", None),
    ("Dashi", ("dashi powder",), "Other", "each", "teaspoon", None),
    ("Bonito Flakes", (), "Other", "package", "cup", None),
    ("Gochugaru", ("korean chili flakes",), "Other", "each", "tablespoon", None),
    ("Furikake", (), "Other", "each", "tablespoon", None),
    ("Falafel Mix", (), "Other", "box", "cup", None),
    ("Hummus", (), "Other", "each", "cup", None),
    ("Tzatziki", (), "Other", "each", "cup", None),
    ("Injera", (), "Other", "package", "each", None),
    ("Masa Harina", (), "Other", "pound", "cup", None),
    ("Almond Butter", (), "Other", "each", "tablespoon", None),
    ("Cashew Butter", (), "Other", "each", "tablespoon", None),
    ("Nutella", ("chocolate hazelnut spread",), "Other", "each", "tablespoon", None),
]

GROCERY_REFERENCE: list[dict] = [
    {
        "name": row[0],
        "aliases": list(row[1]),
        "category": row[2],
        "purchase_unit": row[3],
        "stock_unit": row[4],
        "factor": row[5],
    }
    for row in _RAW_REFERENCE_ROWS
]
